version: '3.8'
services:
  # Backend API
  atlastech-backend:
    build:
      context: ./atlastech-backend
      dockerfile: Dockerfile
    container_name: atlastech-backend
    ports:
      - "8080:80"
    environment:
      - APP_NAME=AtlasTech
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=base64:Guycw2K728RHaKqECZ5MmbXCbDULQX31rDN61iL/OXw=
      - APP_URL=http://13.62.211.220:8080
      - FRONTEND_URL=http://13.62.211.220
      - DB_CONNECTION=mysql
      - DB_HOST=atlascommercial.c1u4ayqi0rzj.eu-north-1.rds.amazonaws.com
      - DB_PORT=3306
      - DB_DATABASE=atlascommercial
      - DB_USERNAME=admin
      - DB_PASSWORD=33Qlpbtx7iYARTPO
      - SESSION_DRIVER=database
      - CACHE_DRIVER=file
      - CORS_ALLOWED_ORIGINS=http://13.62.211.220
      - SANCTUM_STATEFUL_DOMAINS=13.62.211.220
    networks:
      - atlas-network

  # Frontend
  atlastech-frontend:
    build:
      context: ./atlastech-frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://13.62.211.220:8080/api
    container_name: atlastech-frontend
    ports:
      - "80:80"
    networks:
      - atlas-network
    depends_on:
      - atlastech-backend

networks:
  atlas-network:
    driver: bridge
