name: DAST Security Scan

on:
  push:
    branches: [main]

jobs:
  dast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.7.0
        with:
          target: 'https://atlascyber.viewdns.net'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
